### ISSUE TITLE
throughout using simd

### ISSUE THREAD

**Issue by nan2088** [zurutech/pillow-resize#10]
Hi, is there anyone can use simd to speedup the resize process?    for example: [ref](https://github.com/uploadcare/pillow-simd). The throughout seems a little lower than opencv.

**Comment by marcov868** [comment]
Hi, it could be a really interesting feature to add to the library.
We haven't much experience in this kind of optimization, but we can take a look at the library you shared and use it as a reference.
Unfortunately, we have not planned any update of the library in the short term, so I cannot tell you when this kind of feature could be available.
But, we are happy if you are willing to contribute
