### ISSUE TITLE
gtest failed 

### ISSUE THREAD

**Issue by lzcchl** [zurutech/pillow-resize#18]
when I run resize_tests, the log is: 

[==========] Running 24 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 24 tests from ResizeGroup/ResizeTest
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/0
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/0, where GetParam() = ([600 x 400], 0) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/1
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/1, where GetParam() = ([600 x 400], 1) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/2
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/2, where GetParam() = ([600 x 400], 2) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/3
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/3, where GetParam() = ([600 x 400], 3) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/4
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/4, where GetParam() = ([600 x 400], 4) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/5
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/5, where GetParam() = ([600 x 400], 5) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/6
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/6, where GetParam() = ([1200 x 1000], 0) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/7
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/7, where GetParam() = ([1200 x 1000], 1) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/8
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/8, where GetParam() = ([1200 x 1000], 2) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/9
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/9, where GetParam() = ([1200 x 1000], 3) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/10
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/10, where GetParam() = ([1200 x 1000], 4) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualColor/11
unknown file: Failure
C++ exception with description "Height and width must be > 0" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/11, where GetParam() = ([1200 x 1000], 5) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/0
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/0, where GetParam() = ([600 x 400], 0) (1 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/1
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/1, where GetParam() = ([600 x 400], 1) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/2
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/2, where GetParam() = ([600 x 400], 2) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/3
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/3, where GetParam() = ([600 x 400], 3) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/4
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/4, where GetParam() = ([600 x 400], 4) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/5
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/5, where GetParam() = ([600 x 400], 5) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/6
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/6, where GetParam() = ([1200 x 1000], 0) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/7
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/7, where GetParam() = ([1200 x 1000], 1) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/8
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/8, where GetParam() = ([1200 x 1000], 2) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/9
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/9, where GetParam() = ([1200 x 1000], 3) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/10
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/10, where GetParam() = ([1200 x 1000], 4) (0 ms)
[ RUN      ] ResizeGroup/ResizeTest.TestEqualGray/11
unknown file: Failure
C++ exception with description "OpenCV(4.8.0) /home/zhicheng.luo/soft/opcv/opencv-4.8.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
" thrown in the test body.
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/11, where GetParam() = ([1200 x 1000], 5) (0 ms)
[----------] 24 tests from ResizeGroup/ResizeTest (2 ms total)

[----------] Global test environment tear-down
[==========] 24 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 24 tests, listed below:
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/0, where GetParam() = ([600 x 400], 0)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/1, where GetParam() = ([600 x 400], 1)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/2, where GetParam() = ([600 x 400], 2)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/3, where GetParam() = ([600 x 400], 3)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/4, where GetParam() = ([600 x 400], 4)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/5, where GetParam() = ([600 x 400], 5)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/6, where GetParam() = ([1200 x 1000], 0)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/7, where GetParam() = ([1200 x 1000], 1)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/8, where GetParam() = ([1200 x 1000], 2)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/9, where GetParam() = ([1200 x 1000], 3)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/10, where GetParam() = ([1200 x 1000], 4)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualColor/11, where GetParam() = ([1200 x 1000], 5)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/0, where GetParam() = ([600 x 400], 0)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/1, where GetParam() = ([600 x 400], 1)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/2, where GetParam() = ([600 x 400], 2)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/3, where GetParam() = ([600 x 400], 3)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/4, where GetParam() = ([600 x 400], 4)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/5, where GetParam() = ([600 x 400], 5)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/6, where GetParam() = ([1200 x 1000], 0)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/7, where GetParam() = ([1200 x 1000], 1)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/8, where GetParam() = ([1200 x 1000], 2)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/9, where GetParam() = ([1200 x 1000], 3)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/10, where GetParam() = ([1200 x 1000], 4)
[  FAILED  ] ResizeGroup/ResizeTest.TestEqualGray/11, where GetParam() = ([1200 x 1000], 5)

24 FAILED TESTS

**Comment by marcov868** [comment]
It seems it cannot open the images, it's like the paths do not exist.
What is the command you are using to run the tests? And from which path?

**Comment by lzcchl** [comment]
I don't know what command to enter, yes, I didn't fill in the image path. Can you provide a case study on the parameters entered in the command

**Comment by marcov868** [comment]
As stated in the [readme](https://github.com/zurutech/pillow-resize?tab=readme-ov-file#test), the simplest way is to run the tests through make:
```cmake
cmake -DBUILD_TESTS=ON ..
make
make test
```
