### ISSUE TITLE
how to Anti-alias

### ISSUE THREAD

**Issue by TanFluent** [zurutech/pillow-resize#8]
hello, i follow your code and trying to find how to "anti-alias". But not a clue.  Could your plz, common it on code or apply some ref. on your "anti-alias" methods.  Many thx!!! @marcov868

**Comment by marcov868** [comment]
The library is basically just a porting in c++ of the method `resize` from the python library Pillow. So, for each detail, you can refer to their [documentation](https://pillow.readthedocs.io/en/stable/reference/Image.html?highlight=resize#PIL.Image.Image.resize).

TL;DR: If you used the method `PillowResize::resize()`, you're already using an anti-aliasing filter.
